 "use client";
import { useEffect,useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { useParams } from "next/navigation";
import Link from "next/link";

export default function WorkspacePage(){const {slug}=useParams<{slug:string}>();const supabase=createClient();const [w,setW]=useState<any>(null),[members,setMembers]=useState<any[]>([]),[groups,setGroups]=useState<any[]>([]),[tab,setTab]=useState("inbox"),[error,setError]=useState("");
 useEffect(()=>{(async()=>{const {data:w}=await supabase.from("workspaces").select("*").eq("slug",slug).single();setW(w);if(w){const [m,g]=await Promise.all([supabase.from("workspace_members").select("*,profiles(username,display_name)").eq("workspace_id",w.id),supabase.from("workspace_groups").select("*").eq("workspace_id",w.id)]);setMembers(m.data||[]);setGroups(g.data||[])}})()},[slug]);
 if(!w)return <div>Loading workspace…</div>;return <div className="mx-auto max-w-3xl"><Link href="/workspaces" className="text-sm font-bold text-relay-muted">← Workspaces</Link><div className="mt-5"><p className="text-sm font-bold uppercase tracking-[.2em] text-relay-orange">Workspace</p><h1 className="mt-2 text-3xl font-black">{w.name}</h1><p className="text-relay-muted">@{w.slug}</p></div><div className="mt-7 flex gap-2 border-b border-relay-line">{["inbox","members","groups"].map(x=><button key={x} onClick={()=>setTab(x)} className={`px-4 py-3 text-sm font-bold ${tab===x?"border-b-2 border-relay-orange text-relay-orange":"text-relay-muted"}`}>{x[0].toUpperCase()+x.slice(1)}</button>)}</div>{tab==="members"&&<div className="mt-4 space-y-2">{members.map(m=><div className="card flex justify-between p-4" key={m.id}><div><p className="font-bold">{m.profiles?.display_name}</p><p className="text-sm text-relay-muted">@{m.profiles?.username}</p></div><span className="text-xs font-bold text-relay-muted">{m.role}</span></div>)}</div>}{tab==="groups"&&<div className="mt-4 space-y-2">{groups.map(g=><div className="card p-4" key={g.id}><p className="font-bold">{g.name}</p><p className="text-sm text-relay-muted">@{w.slug}_{g.slug}</p></div>)}</div>}{tab==="inbox"&&<div className="card mt-4 p-6"><p className="font-bold">Workspace inbox</p><p className="mt-2 text-sm text-relay-muted">Files sent to @{w.slug} are fan-out deliveries to workspace members.</p></div>}</div>}
