 "use client";
import { useEffect,useState } from "react";
import { createClient } from "@/lib/supabase/client";
import Link from "next/link";

export default function WorkspacesPage(){const supabase=createClient();const [items,setItems]=useState<any[]>([]);const [name,setName]=useState(""),[slug,setSlug]=useState(""),[show,setShow]=useState(false),[error,setError]=useState("");
 async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user)return;const owned=await supabase.from("workspaces").select("*").eq("owner_id",user.id).order("created_at",{ascending:false}); const memberships=await supabase.from("workspace_members").select("workspace_id").eq("user_id",user.id); const ids=(memberships.data||[]).map((m:any)=>m.workspace_id); const joined=ids.length?await supabase.from("workspaces").select("*").in("id",ids):{data:[]}; const map=new Map<string,any>(); [...(owned.data||[]),...(joined.data||[])].forEach((x:any)=>map.set(x.id,x)); setItems([...map.values()])}
 useEffect(()=>{load()},[]);
 async function create(){setError("");const clean=slug.toLowerCase().replace(/^@/,"");const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data,error}=await supabase.from("workspaces").insert({name,slug:clean,owner_id:user.id}).select().single();if(error){setError(error.message);return;}await supabase.from("workspace_members").insert({workspace_id:data.id,user_id:user.id,role:"admin"});setShow(false);setName("");setSlug("");load()}
 return <div className="mx-auto max-w-3xl"><div className="mb-7 flex items-end justify-between"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-relay-orange">Workspaces</p><h1 className="mt-2 text-3xl font-black">Your teams.</h1></div><button onClick={()=>setShow(true)} className="btn-primary">Create workspace</button></div><div className="space-y-3">{items.map(w=><Link href={`/workspaces/${w.slug}`} key={w.id} className="card block p-5 hover:shadow-lg"><p className="font-black">{w.name}</p><p className="text-sm text-relay-muted">@{w.slug}</p></Link>)}{!items.length&&<div className="card p-8 text-center text-relay-muted">No workspaces yet.</div>}</div>{show&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/30 p-5"><div className="card w-full max-w-md p-6"><h2 className="text-xl font-black">Create workspace</h2><input className="input mt-4" placeholder="Workspace name" value={name} onChange={e=>setName(e.target.value)}/><input className="input mt-3" placeholder="slug" value={slug} onChange={e=>setSlug(e.target.value)}/>{error&&<p className="mt-3 text-sm text-red-600">{error}</p>}<div className="mt-5 flex gap-3"><button onClick={()=>setShow(false)} className="btn-secondary flex-1">Cancel</button><button onClick={create} className="btn-primary flex-1">Create</button></div></div></div>}</div>}
